### PR TITLE
adding binomial coefficient

### PR DESCRIPTION
**Pull request by Rohankumar2804**
binomial coefficient added with proper variable name and function
problem link
https://cses.fi/problemset/result/1078353/

### CODE REVIEW

**Comment by suvidsahay** [comment]
Check your previous PRs, I did some changes. Go through it again.
There are still many formatting changes to be made.

**Comment by Rohankumar2804** [comment]
thanks sir i didnt provided proper indentation int nck function

**Comment by suvidsahay** [comment]
> thanks sir i didnt provided proper indentation int nck function

And also you need to provide proper spacing too.
Once you have done that try learning about squashing commits and send the PR to this solution with a single commit.

**Comment by Rohankumar2804** [comment]
okk sir i will try thanks you so much sir for your valuable suggestion and help

**Comment by suvidsahay** [comment]
Proper indentation and spacing still missing.
Check the previous commit or follow [this](https://google.github.io/styleguide/cppguide.html#Formatting) link

**Comment by suvidsahay** [comment]
Your indentations are not again proper. Fixing it for the last time. 
Please carefully review the changes and try to follow the same standards everywhere.

**Pull request merged**
